# Generated by Django 4.2.17 on 2024-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_car_bodytype_car_color_car_condition_car_enginepower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='area',
        ),
        migrations.AddField(
            model_name='realestate',
            name='balcony',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='realestate',
            name='buildingAge',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='deposit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='dues',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestate',
            name='floor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='grossArea',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='heating',
            field=models.CharField(choices=[('Central', 'Central Heating'), ('Individual', 'Individual Heating'), ('None', 'No Heating')], default='Central', max_length=255),
        ),
        migrations.AddField(
            model_name='realestate',
            name='insideSite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestate',
            name='kitchen',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='realestate',
            name='netArea',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestate',
            name='roomCount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='realestate',
            name='sellerType',
            field=models.CharField(default='Owner', max_length=50),
        ),
        migrations.AddField(
            model_name='realestate',
            name='totalFloors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], default='Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='heavyDamage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='swap',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='traction',
            field=models.CharField(choices=[('FWD', 'Front-Wheel Drive'), ('RWD', 'Rear-Wheel Drive'), ('AWD', 'All-Wheel Drive'), ('4WD', 'Four-Wheel Drive')], default='FWD', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='warranty',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='property_type',
            field=models.CharField(choices=[('Apartment', 'Apartment'), ('Villa', 'Villa'), ('Office', 'Office')], default='Apartment', max_length=50),
        ),
    ]
