# Generated by Django 4.2.17 on 2024-12-07 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_realestate_area_realestate_balcony_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='sellerType',
            field=models.CharField(default='Owner', max_length=50),
        ),
    ]
