# Generated by Django 4.2.17 on 2024-12-07 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_realestate_sellertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realestate',
            old_name='sellerType',
            new_name='seller',
        ),
    ]
