# Generated by Django 4.2.17 on 2024-12-07 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_sellertype_realestate_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='seller',
        ),
    ]
