# Generated by Django 4.2.17 on 2024-12-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_realestate_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.CharField(choices=[('Otomobil', 'Otomobil'), ('Elektrikli Araçlar', 'Elektrikli Araçlar'), ('Deniz Araçları', 'Deniz Araçları'), ('Minivan', 'Minivan')], default='Otomobil', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Sıfır', 'Sıfır'), ('2. El', '2. El'), ('Hasarlı', 'Hasarlı')], default='Sıfır', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Benzin', 'Benzin'), ('Dizel', 'Dizel'), ('Hibrit', 'Hibrit'), ('Elektrik', 'Elektrik')], default='Benzin', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='traction',
            field=models.CharField(choices=[('Önden Çekiş', 'Önden Çekiş'), ('Arkadan İtiş', 'Arkadan İtiş')], default='FWD', max_length=100),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='property_type',
            field=models.CharField(choices=[('Konut', 'Konut'), ('İş Yeri', 'İş Yeri'), ('Arsa', 'Arsa'), ('Konut Projeleri', 'Konut Projeleri'), ('Bina', 'Bina'), ('Devre Mülk', 'Devre Mülk')], default='Apartment', max_length=50),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='seller',
            field=models.CharField(choices=[('Sahibinden', 'Sahibinden'), ('Emlakçı', 'Emlakçı')], default='Sahibinden', max_length=50),
        ),
    ]
