# Generated by Django 4.2.17 on 2024-12-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_car_category_alter_car_condition_alter_car_fuel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Sıfır', 'Sıfır'), ('İkinci El', 'İkinci El'), ('Hasarlı', 'Hasarlı')], default='Sıfır', max_length=20),
        ),
    ]
