# Generated by Django 4.2.17 on 2024-12-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_car_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(default='car', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='realestate',
            name='type',
            field=models.CharField(default='estate', editable=False, max_length=10),
        ),
    ]
