# Generated by Django 4.2.17 on 2024-12-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_car_type_realestate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='category',
            field=models.CharField(default='Konut', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='category',
            field=models.CharField(default='Otomobil', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(default='Sıfır', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(default='Benzin', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(default='Manual', max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='traction',
            field=models.CharField(default='FWD', max_length=100),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='heating',
            field=models.CharField(default='Central', max_length=255),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='property_type',
            field=models.CharField(default='Apartment', max_length=50),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='seller',
            field=models.CharField(default='Sahibinden', max_length=50),
        ),
    ]
